
server:
  port: 9000

# MYSQL DB Connection
spring:
  application:
    name: socialNetwork
  jpa:
    hibernate:
      ddl-auto : update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_com_db
    username: root
    password: password

#H2 DB Connection
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName : org.h2.Driver
#    username : root
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
