
server:
  port: 9000

#DB Connection
spring:
  application:
    name: socialNetwork
  jpa:
    hibernate:
      ddl-auto : update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_com_db
    username: root
    password: password
